### ISSUE TITLE
Evento frog não finaliza

### ISSUE THREAD

**Issue by pump61** [Ars3ne/aEventos#1]
O evento não finaliza quando tem a ultima pessoa viva, estou usando a ultima versão do plugin.

Na versão 1.16.5

**Comment by Ars3ne** [comment]
O evento Frog acaba quando um jogador sobe em cima da lã vermelha, que é gerada quando sobra apenas um tipo de bloco.

Agora, caso os jogadores não sejam eliminados ao tocarem na água, isso sim é um bug. Estarei esperando mais informações.

**Comment by pump61** [comment]
No final a lã vermelha não aparece, o último bloco que fica vira gelo e some e ninguém vence o evento, passei a tarde testando com os players do meu servidor, o evento deveria terminar quando só tivesse um player vivo não acontece, e se tivesse mais de um vivo aí sim a lã deveria aparecer tbm não tá funcionando. Se vc quiser ver e testar comigo só falar que eu mostro tudo certinho

**Comment by Ars3ne** [comment]
Infelizmente eu não posso testar esse potencial bug no momento porque estou sem um computador, porém acredito que conseguirei arrumar-lo em breve. Irei postar um novo comentário quando tiver algum progresso.

**Comment by pump61** [comment]
Vlw pela atenção!

**Comment by pump61** [comment]
Ars3ne vc me consegue seu contato pelo discord?

**Comment by Ars3ne** [comment]
Acredito que consegui resolver o problema. Me adicione no Discord para obter a nova versão: ``Ars3ne#0497``

**Comment by pump61** [comment]
adicionei

**Comment by Ars3ne** [comment]
Bug corrigido no commit 4dac0efdf6e7ee46728b94b2b339f04932f11d67.
