### ISSUE TITLE
Sugestões para o Hunter

### ISSUE THREAD

**Issue by thiagogebrimm** [Ars3ne/aEventos#2]
Adicionar inquebrável no arco e se um time desiste do evento ele não entrega a vitória ao outro time

**Comment by Ars3ne** [comment]
Eu até posso adicionar o inquebrável aos arcos, mas eu não entendi muito bem o que a sua segunda sugestão significa.

**Comment by thiagogebrimm** [comment]
> Eu até posso adicionar o inquebrável aos arcos, mas eu não entendi muito bem o que a sua segunda sugestão significa.

Estava rolando o evento e em meu servidor e eu defino 100 pontos para finalizar, era em um horário vazio e tinha apenas 4 no evento, 2 em cada time, um desistiu e o outro quebrou o arco e teve que desistir, e quando os 2 desistiram o evento bugou e não declarou vitória ao time que ficou vivo, e ai tiveram que todos sair do evento para ele ser cancelado.

**Comment by Ars3ne** [comment]
Ah sim, eu me esqueci de colocar essa funcionalidade. Infelizmente estou muito ocupado no momento e pode demorar alguns dias para que eu possa adicionar as suas sugestões.

**Comment by thiagogebrimm** [comment]
Sem problemas, e muito obrigado

**Comment by Ars3ne** [comment]
Corrigido no commit f19534d.
