### ISSUE TITLE
to com um problema os enventos nao aparecem para os jogadores

### ISSUE THREAD

**Issue by Joaofixe** [Ars3ne/aEventos#5]
os eventos nao aparecem in game apenas o fastclick e eu nao sei o porque poderia me ajudar

**Comment by Ars3ne** [comment]
Você poderia me fornecer mais informações sobre o erro? Quais eventos não "estão aparecendo in-game"? Você configurou eles usando o comando /evento setup?

**Comment by Joaofixe** [comment]
os eventos de chat por exemplo nao aparecem so o fastclick.
porem para staffs com op todos aparecem

**Comment by Ars3ne** [comment]
O evento não aparece no chat ou os jogadores não conseguem participar dele? Se for o segundo caso, os jogadores precisam de uma permissão que por padrão é "aeventos.evento" para todos os eventos.

**Comment by Joaofixe** [comment]
nao aparece no chat

**Comment by Ars3ne** [comment]
Você já deu uma olhada no console para ver se tem algum erro? Também seria bom verificar se voce tem o Vault e um plugin de economia instalados, porque vários eventos de chat tem esse requisito.

**Comment by Joaofixe** [comment]
temos vault e plugin de economia e no console tem nenhum erro e relaçao a isso. por isso que entrei em contato com vc.

**Comment by Ars3ne** [comment]
Eu nao tenho nenhuma ideia do porque isso está acontecendo. Eu gostaria que você me desse alguns detalhes para me ajudar:

- A versão do Plugin que está utilizando.
- A versão do Minecraft que o servidor está rodando.
- Lista dos eventos que você testou e não apareceram no chat (Algo mais claro que "eventos de chat")
-  Qual maneira você está usando para iniciar os eventos? (/evento iniciar <evento> ou pelo AutoStarter)
-  Qual plugin de chat você está usando.

**Comment by Joaofixe** [comment]
versao do plugin : 1.5.1
versao do mine : 1.17.1
eventos que nao aparecem: plavara, matematica, loteria, bolao.
eu tenho o autostarter configurado e alguns e com /evento iniciar
plugin de chat e o nchat.
o unico evento que funciona e o fastclick.

**Comment by Joaofixe** [comment]
o que acha que possa ser ?

**Comment by Ars3ne** [comment]
Desculpe pela demora para responder, mas infelizmente eu não consegui reproduzir o seu erro. Você poderia tentar gravar  um vídeo mostrando o erro acontecendo?

**Comment by Ars3ne** [comment]
Fechado por inatividade.
