### ISSUE TITLE
Não é possível setar as pos do sumo

### ISSUE THREAD

**Issue by CPUFAEL** [Ars3ne/aEventos#8]
Não é possível setar as posições do sumo. Ao utilizar o comando /evento setup pos 
Aparece que não é necessario o uso do machado. E quando digito ;evento setup pos(1-4) da a mesma mensagem, como resolvo?

**Comment by Ars3ne** [comment]
O evento Sumô não é um evento 1v1 e por isso não é possível definir essas posições. Caso você queira criar um evento sumô 1v1, basta copiar o arquivo do evento Fight e o configurar usando o comando /evento setup <nome do novo arquivo sem .yml>

**Comment by CPUFAEL** [comment]
Genial ksks

**Comment by CPUFAEL** [comment]
Referente a derrota. Como funciona? É com agua, void?

**Comment by Ars3ne** [comment]
Em eventos de eliminação (Campo Minado, Frog, Sumo, etc) o jogador é eliminado ao cair na água. Nos outros eventos ele é eliminado ao morrer (seja por um jogador ou pelo void)

Eu estarei fechando essa issue porque ela aparentemente foi resolvida. Caso tenha algum outro problema crie uma nova issue ou entre em contato no meu Discord: arsenismo
